// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWfOlvD4tcRulcqv5E9KxVsWRyLzBr_PI',
    appId: '1:663291565024:web:f3b420121f2b0001129185',
    messagingSenderId: '663291565024',
    projectId: 'ex10workout-56a23',
    authDomain: 'ex10workout-56a23.firebaseapp.com',
    storageBucket: 'ex10workout-56a23.firebasestorage.app',
    measurementId: 'G-XJ9JJ1ML1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk4c6RV8BAiDIqZQoXp4d1ix49TYWKeD8',
    appId: '1:663291565024:android:05ef78a9f432b9ef129185',
    messagingSenderId: '663291565024',
    projectId: 'ex10workout-56a23',
    storageBucket: 'ex10workout-56a23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp0alMeGLpGv2U-0PXFBBHiq4cPgEek9k',
    appId: '1:663291565024:ios:559cf5b161f7c2de129185',
    messagingSenderId: '663291565024',
    projectId: 'ex10workout-56a23',
    storageBucket: 'ex10workout-56a23.firebasestorage.app',
    iosBundleId: 'com.example.ex10WorkoutFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp0alMeGLpGv2U-0PXFBBHiq4cPgEek9k',
    appId: '1:663291565024:ios:559cf5b161f7c2de129185',
    messagingSenderId: '663291565024',
    projectId: 'ex10workout-56a23',
    storageBucket: 'ex10workout-56a23.firebasestorage.app',
    iosBundleId: 'com.example.ex10WorkoutFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWfOlvD4tcRulcqv5E9KxVsWRyLzBr_PI',
    appId: '1:663291565024:web:c772b6cf767d29be129185',
    messagingSenderId: '663291565024',
    projectId: 'ex10workout-56a23',
    authDomain: 'ex10workout-56a23.firebaseapp.com',
    storageBucket: 'ex10workout-56a23.firebasestorage.app',
    measurementId: 'G-YHHVSRZ3WM',
  );
}
