// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACYfBeKgML2tZZhBeNFtORV20aVg1YuFk',
    appId: '1:757498822769:web:acbf264621bd7dc7e35bd0',
    messagingSenderId: '757498822769',
    projectId: 'test2-garagesales',
    authDomain: 'test2-garagesales.firebaseapp.com',
    storageBucket: 'test2-garagesales.firebasestorage.app',
    measurementId: 'G-WVGE7EJBGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrusz9_9yrYu6vPIjE-0hXcf3a4DwgGdo',
    appId: '1:757498822769:android:27acd8c9a79702f0e35bd0',
    messagingSenderId: '757498822769',
    projectId: 'test2-garagesales',
    storageBucket: 'test2-garagesales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlIAUyFuv4nM8LElUScUewIW5FS2T0rYw',
    appId: '1:757498822769:ios:02360b5d0c6ee0d9e35bd0',
    messagingSenderId: '757498822769',
    projectId: 'test2-garagesales',
    storageBucket: 'test2-garagesales.firebasestorage.app',
    iosBundleId: 'com.example.test2GaragesaleDylane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlIAUyFuv4nM8LElUScUewIW5FS2T0rYw',
    appId: '1:757498822769:ios:02360b5d0c6ee0d9e35bd0',
    messagingSenderId: '757498822769',
    projectId: 'test2-garagesales',
    storageBucket: 'test2-garagesales.firebasestorage.app',
    iosBundleId: 'com.example.test2GaragesaleDylane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACYfBeKgML2tZZhBeNFtORV20aVg1YuFk',
    appId: '1:757498822769:web:0ded98510ca05d38e35bd0',
    messagingSenderId: '757498822769',
    projectId: 'test2-garagesales',
    authDomain: 'test2-garagesales.firebaseapp.com',
    storageBucket: 'test2-garagesales.firebasestorage.app',
    measurementId: 'G-XY2ZM53YQC',
  );
}
