// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF16i1-Qj_s8soVCNCvtL8yaPme_Vufpg',
    appId: '1:772186724035:web:e8f4e380e46c06d387b476',
    messagingSenderId: '772186724035',
    projectId: 'fireapp-64701',
    authDomain: 'fireapp-64701.firebaseapp.com',
    storageBucket: 'fireapp-64701.firebasestorage.app',
    measurementId: 'G-376ZHPCSWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhFlJtSd_B_n_LO_6__aeuOdLUxHQEyY',
    appId: '1:772186724035:android:11b0fa389df76fdf87b476',
    messagingSenderId: '772186724035',
    projectId: 'fireapp-64701',
    storageBucket: 'fireapp-64701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZvjti3OMGK_RUixifTesLd_CnrpeoyI',
    appId: '1:772186724035:ios:f4ab8c53c227e4ba87b476',
    messagingSenderId: '772186724035',
    projectId: 'fireapp-64701',
    storageBucket: 'fireapp-64701.firebasestorage.app',
    iosBundleId: 'com.example.fireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUZvjti3OMGK_RUixifTesLd_CnrpeoyI',
    appId: '1:772186724035:ios:f4ab8c53c227e4ba87b476',
    messagingSenderId: '772186724035',
    projectId: 'fireapp-64701',
    storageBucket: 'fireapp-64701.firebasestorage.app',
    iosBundleId: 'com.example.fireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF16i1-Qj_s8soVCNCvtL8yaPme_Vufpg',
    appId: '1:772186724035:web:f3ddf0dfea578ca287b476',
    messagingSenderId: '772186724035',
    projectId: 'fireapp-64701',
    authDomain: 'fireapp-64701.firebaseapp.com',
    storageBucket: 'fireapp-64701.firebasestorage.app',
    measurementId: 'G-H22H51804C',
  );
}
